### ISSUE TITLE
assignUserToApplication method expects AppUser object

### ISSUE THREAD

**Issue by Sara3** [okta/okta-sdk-java#322] opened 2019-09-30 20:39 UTC
```java
public AppUser getAppUsers2(User user) {

    System.out.println(user.getId());
    AppUser appUser = client.instantiate(AppUser.class)
    .setScope("USER")
    .setId(user.getId())
    .setCredentials(client.instantiate(AppUserCredentials.class)
        .setUserName(user.getProfile().getEmail())
        .setPassword(client.instantiate(AppUserPasswordCredential.class)
            .setValue("super-secret2".toCharArray())));

    System.out.print(appUser);
    return appUser;

}
```
the above returns null

**Comment by bdemers** [comment] 2019-09-30 20:56
@Sara3 I'm not sure I'm following? Are you saying `setCredentials` is returning null?
What version are you using?

**Comment by countonit-t** [comment] 2019-10-15 12:34
Hey

Essentially, what we are trying to do is assign a user directly to an app in Okta. The Application.assignUserToApplication requires an input of AppUser object. I tried the following per Sara's recommendation:

	public AppUser getAppUsers2(User user) {
		System.out.println(user.getId());
		AppUser appUser = client.instantiate(AppUser.class).setScope("USER").setId(user.getId()).setCredentials(
				client.instantiate(AppUserCredentials.class).setUserName(user.getProfile().getEmail()).setPassword(
						client.instantiate(AppUserPasswordCredential.class).setValue("super-secret2".toCharArray())));
		System.out.print(appUser);
		return appUser;
	}

But i get an empty response. Ideally, we'd like to assign a user to application by just providing the user id to Application.assignUserToApplication.

**Comment by bdemers** [comment] 2019-10-15 19:56
@countonit-t What method returns an empty response?

**Comment by countonit-t** [comment] 2019-10-16 16:31
@bdemers the System.out.print(appUser); returns nothing.

**Comment by bdemers** [comment] 2019-10-16 17:15
@countonit-t, sorry, just trying to double-check, are you saying it's `null` or an empty string is printed?

To help narrow it down have you tried to remove a few of the lines? or break up the creation of the nested objects?

For example:
```java
AppUser appUser = client.instantiate(AppUser.class)
    .setScope("USER")
    .setId(user.getId());

AppUserCredentials appUserCreds = client.instantiate(AppUserCredentials.class)
        .setUserName(user.getProfile().getEmail()));

appUser. setCredentials(appUserCreds);
```

Or something like that.

**Comment by countonit-t** [comment] 2019-10-18 13:51
Hey @bdemers 

Copied your code and tried that a bit as well but still nothing is being returned fo appuser. I am not sure if i am going about this the wrong way. But all i am trying to do is simply add a user to an app. I found a currently non scalable way to get this to work: it involved:
Finding an application currently owned by UserA (Lets call the app AppA). 
Call a list of users in AppA (this returns and interable list of appusers)
Find the appuser object for UserA
Then assign the appuser object found for UserA to AppB

That logic was not approved by the team and raised a few questions.

**Comment by bdemers** [comment] 2019-10-18 13:58
@countonit-t 
Sorry, I think I'm missing where the problem is, and I'm not 100% sure of what you mean by "nothing is being returned to appuser".

Let's take a step back, and use more specific terms. 
With the last example you tried, is there a line that is returning null?

**Comment by countonit-t** [comment] 2019-10-28 17:59
Apologies for the delays in response. The System.out.print(appUser) line returns nothing in my response. If feasible, can we set up a quick call to go over the use case? I can also share my screen to show what I am seeing on my end.

Thanks

**Comment by bdemers** [comment] 2019-11-04 19:46
@countonit-t nothing as in `null` or empty text?

**Comment by countonit-t** [comment] 2019-11-05 13:47
@bdemers empty text

**Comment by bdemers** [comment] 2019-11-05 17:39
I'm not sure why `appUser.toString()` would return an empty string offhand, but assuming it is non-null you should be fine.

What happens when you actually create the user? are you getting an error?

**Comment by countonit-t** [comment] 2019-11-08 18:50
Brian

The user already exist. We are just trying to add the user to an application that requires several attributes. Essentially, we are trying to do what the api in the attached screenshot does via the okta sdk. The problem is that I have not seen a way to convert a user object to an app user object. 

 
![Screen Shot 2019-11-08 at 1 47 39 PM](https://user-images.githubusercontent.com/56591843/68502421-5b325d80-022e-11ea-9ec3-c469babe691d.png)

**Comment by bdemers** [comment] 2019-11-10 16:02
In the Postman example, it looks like the AppUser assignment already exists, are you just trying to update t?

**Comment by arvindkrishnakumar-okta** [comment] 2020-07-07 18:26
Closing this issue now. Please reopen if you still need support on this one.

**Closed by arvindkrishnakumar-okta** 2020-07-07 18:26 UTC
Labels: question
