### ISSUE TITLE
Cannot update profile with array properties returned by user API

### ISSUE THREAD

**Issue by JFreakDK** [okta/okta-sdk-java#858] opened 2023-04-20 08:51 UTC
### Describe the bug?

The profile object returned by the user API does not work with UpdateUserRequest.
This code fails when the profile has custom array properties.
```
        UserApi userApi = new UserApi(client);
        var user = userApi.getUser(userId);
        UserProfile profile = user.getProfile();
        UpdateUserRequest request = new UpdateUserRequest().profile(profile);
        userApi.replaceUser(userId, request, null);
```

### What is expected to happen?

The `userApi.replaceUser(userId, request, null);` call should execute succesfully.

### What is the actual behavior?

```
com.okta.sdk.error.ResourceException: HTTP 400, Okta E0000001 (Api validation failed: userProfile - '3 causes'), ErrorId <error-id>

	at com.okta.sdk.error.ErrorHandler.handleError(ErrorHandler.java:114)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:825)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:783)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:676)
	at org.openapitools.client.ApiClient.lambda$invokeAPI$3(ApiClient.java:750)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:329)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:209)
	at org.openapitools.client.ApiClient.invokeAPI(ApiClient.java:750)
	at org.openapitools.client.api.UserApi.replaceUserWithHttpInfo(UserApi.java:3613)
	at org.openapitools.client.api.UserApi.replaceUser(UserApi.java:3535)
...
```
The http response contains these details:
```
{"errorCode":"E0000001","errorSummary":"Api validation failed: userProfile","errorLink":"E0000001","errorId":"<error-id>","errorCauses":[{"errorSummary":"Invalid value data type for property '<array property>'"},{"errorSummary":"Invalid value data type for property '<array property>'"},{"errorSummary":"Invalid value data type for property '<array property>'"}]}
```

### Reproduction Steps?

```
        UserApi userApi = new UserApi(client);
        var user = userApi.getUser(userId);
        UserProfile profile = user.getProfile();
        UpdateUserRequest request = new UpdateUserRequest().profile(profile);
        userApi.replaceUser(userId, request, null);
```

### Additional Information?

Doing this update using the REST API directly works.

It is unclear how array properties are supported by the API. Should the value of the additional property be a java.util.List of values or a string matching the format expected in the raw REST API?

### Java Version

openjdk version "20" 2023-03-21
OpenJDK Runtime Environment Homebrew (build 20)
OpenJDK 64-Bit Server VM Homebrew (build 20, mixed mode, sharing)

### SDK Version

10.2.2

### OS version

Darwin <hostname> 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64 x86_64

**Comment by arvindkrishnakumar-okta** [comment] 2023-04-20 10:50
@JFreakDK Thanks for posting!

Can you try the below (`userApi.updateUser` instead of `replaceUser`)?

```
User user = userApi.getUser(userId);

UserProfile profile = user.getProfile().city("Awesome City");

UpdateUserRequest request = new UpdateUserRequest().profile(profile);

User updatedUser = userApi.updateUser(userId, request, null);

Assert.isTrue(updatedUser.getProfile().getCity().equals("Awesome City"));
```

**Comment by JFreakDK** [comment] 2023-06-16 08:34
@arvindkrishnakumar-okta the example [above](https://github.com/okta/okta-sdk-java/issues/858#issuecomment-1516116955) can recreate the issue.

The user you are getting needs a profile with a [custom attribute](https://help.okta.com/en-us/Content/Topics/users-groups-profiles/usgp-add-custom-user-attributes.htm) with the data type: string array.

**Comment by arvindkrishnakumar-okta** [comment] 2023-06-16 14:17
@JFreakDK Thanks for the info, I'll work on the fix.

**Comment by arvindkrishnakumar-okta** [comment] 2023-07-24 17:13
Tried to reproduce this issue but I find this use case to be working fine.

1. Added a Custom String array attribute (`myStrArr`) to user profile via console UI:

![image](https://github.com/okta/okta-sdk-java/assets/61501885/1070260c-d6ba-4cc4-b4ea-a68dbcbb02f6)

2. Used below code to create a user and update the created user with a value for `myStrArr` profile attribute:

```
UpdateUserRequest updateUserRequest = new UpdateUserRequest()
UserProfile userProfile = new UserProfile()
userProfile.setNickName("Batman")

// Note: Custom user profile properties can be added with something like below, but
// the respective property must first be associated to the User schema.
// You can use the Profile Editor in your Org administrator UI or the Schemas API
// to manage schema extensions.
userProfile.getAdditionalProperties().put("myStrArr", new String[] {"Hello", "World"})

updateUserRequest.setProfile(userProfile)

userApi.updateUser(user.getId(), updateUserRequest, true)

User updatedUser = userApi.getUser(user.getId())
```

updatedUser instance above contains the updated profile attrbute values for `myStrArr`.

Viewing the updated user via console:

![image](https://github.com/okta/okta-sdk-java/assets/61501885/04db00e7-9e9d-403f-9577-722c95e932f5)

**Comment by arvindkrishnakumar-okta** [comment] 2023-07-27 17:03
Will go ahead and close this issue, feel free to reopen if needed.

**Closed by arvindkrishnakumar-okta** 2023-07-27 17:03 UTC
Labels: waiting-for-feedback, OKTA-620006

**Comment by JFreakDK** [comment] 2023-08-07 13:01
I tried to reproduce this issue again with this method:
```
    private void testReplaceUser(UserApi userApi, String userId) {
        var user = userApi.getUser(userId);
        UserProfile profile = user.getProfile();
        assert profile != null;
        userApi.replaceUser(userId, user, null);
    }
```
This causes this exception to be thrown:
```
ApiException{code=400, responseHeaders={...}, responseBody='{"errorCode":"E0000001","errorSummary":"Api validation failed: userProfile","errorLink":"E0000001","errorId":"oaealURtv_KS6q44SFeTLIFFQ","errorCauses":[{"errorSummary":"Invalid value data type for property 'propertyName'"}]}
'}
	at org.openapitools.client.ApiClient.processResponse(ApiClient.java:957)
	at org.openapitools.client.ApiClient.invokeAPI(ApiClient.java:1109)
	at org.openapitools.client.api.UserApi.replaceUser(UserApi.java:2273)
	at org.openapitools.client.api.UserApi.replaceUser(UserApi.java:2215)
```

**Comment by JFreakDK** [comment] 2023-08-07 13:28
@arvindkrishnakumar-okta it looks like your user does not have a list property with values.

That is the case that is failing for me:
![profile](https://github.com/okta/okta-sdk-java/assets/1182908/a60e6413-0657-4a9e-a4bf-f5b810b7d5dc)

**Comment by arvindkrishnakumar-okta** [comment] 2023-08-07 14:11
@JFreakDK can you elaborate on "list property with values"?

I tried with array property and hHere is the sequence:

1) Created a user with custom array property for profile:

```
User   user = UserBuilder.instance()
              .setEmail(email)
              .setFirstName("Joe")
              .setLastName("Coder")
              .setPassword(password)
              .setSecurityQuestion("Favorite security question?")
              .setSecurityQuestionAnswer("None of them!")
              .setCustomProfileProperty("myStrArr", new String[] {"Hello", "World"}) // pre-req: custom profile properties need to be set in your Org's Profile editor via Admin UI.
                .setActive(true)
                .addGroup(group.getId()) // add user to the newly created group
                .buildAndCreate(userApi);
```

2) Fetch the user and change the profile attribute and invoke replaceUser:

```
            User fetchedUser = userApi.getUser(userId);
            UserProfile profile = fetchedUser.getProfile();
            profile.getAdditionalProperties().put("myStrArr", new String[] {"HelloUpdated", "WorldUpdated"});
            User replacedUsr = userApi.replaceUser(userId, fetchedUser, null);
            println("Replaced User: " + replacedUsr);
```

![image](https://github.com/okta/okta-sdk-java/assets/61501885/78970ce5-4f0a-4e64-b524-2040845a74c1)


![image](https://github.com/okta/okta-sdk-java/assets/61501885/364097bb-4cc1-4f2d-9902-04c3db425feb)

**Comment by JFreakDK** [comment] 2023-08-08 08:41
@arvindkrishnakumar-okta your example is almost there. Create the user as described in step 1.
In step 2 do not update the array attribute but another attribute.
```
            User fetchedUser = userApi.getUser(userId);
            UserProfile profile = fetchedUser.getProfile();
            profile.setFirstName("Test");
            User replacedUsr = userApi.replaceUser(userId, fetchedUser, null);
            println("Replaced User: " + replacedUsr);
```

**Comment by arvindkrishnakumar-okta** [comment] 2023-08-08 14:39
@JFreakDK Thanks, I was able to reproduce the error now. 

It looks like the PUT request for replaceUser is not happy seeing the custom array attribute in request body. I did try it out from POSTMAN and I see the same error, so this does not look like it is an SDK error.

When you tried the replaceUser API from POSTMAN, did you have to modify the request body for your request to be successful? Can you paste your POSTMAN request body (with sensitive fields redacted) for which you got a success response?

**Comment by arvindkrishnakumar-okta** [comment] 2023-08-08 21:10
@JFreakDK #932 should fix this.

**Comment by JFreakDK** [comment] 2023-08-09 10:44
I don't see that #932 changes anything related to additional properties.

**Comment by arvindkrishnakumar-okta** [comment] 2023-08-09 12:05
@JFreakDK The PR addresses the issue where the additional property map value was incorrectly deserialized into a String value (we should retain it as an Object and not convert it into String while storing it). I've tested the PR locally. 

Feel free to validate it once the fix has been merged to master (release should be done in few days).

**Comment by JFreakDK** [comment] 2023-08-10 12:31
I can confirm that this worked. Thanks for fixing this.
