### ISSUE TITLE
Feature Request: Support for User Authentication

### ISSUE THREAD

**Issue by sdford** [okta/okta-sdk-java#149] opened 2018-01-24 19:55 UTC
Is there a plan to add User Authentication support (via: username and password, and multi-factor validation) in the client?
https://developer.okta.com/docs/api/resources/authn.html#authentication-operations

The Javascript SDK supports this already:
https://developer.okta.com/code/javascript/okta_auth_sdk

It seems like it would be as simple as adding another method or two (e.g. `authenticateUser`, `validateFactor`) to the `Client` class.
https://developer.okta.com/okta-sdk-java/apidocs/com/okta/sdk/client/Client.html

**Comment by bdemers** [comment] 2018-01-24 20:13
Hey @sdford!

For multi-factor you can currently validate factors with the SDK just call `factor.verify()`

We have been talking about adding user authentication support, but it will likely NOT go in this repository.  In most cases User/Password validation can be replaced with an OAuth flow. Which is great because now your application doesn't need to worry about securely handling passwords (making sure they are not in any access logs or stack traces, for example).

That said, we understand it would make things easier to integrate with legacy applications.  Is there something specific you are trying to integrate with?

Closing duplicate of #106

**Closed by bdemers** 2018-01-24 20:13 UTC

**Comment by sdford** [comment] 2018-01-25 00:31
@bdemers,

Is there an ETA on the user authentication support? Is it only a consideration, not a definite?

Yes, we are looking to integrate with a non-Spring Java microservice for Cerberus.

OAuth isn't a bad option, but would require a little more work considering we have an older version of the Okta Java SDK already working with user authentication. Also, we have other services that rely on our backend (which uses the Okta Java SDK) for authentication and authorization through Okta.

Thanks for the heads up about multi-factor. I missed that in the docs.

**Comment by bdemers** [comment] 2018-01-25 14:37
The old Okta SDK uses a different namespace (java package and Maven gav), so you should be able to keep using it while you migrate to the current one.

We don't have a time frame on this, but I'll probably be poking around more in the next few weeks.  So, if you have any thoughts/ideas on the topic let me know!

**Comment by EarthCitizen** [comment] 2019-03-17 09:42
@bdemers It looks like the okta-auth-java project will not have a stable release until long after 0.4.0 is retired :-/

**Comment by bdemers** [comment] 2019-03-18 15:16
@EarthCitizen you mean `0.0.4`? 
I don't think we will see any big changes before a 1.0.  I'd like to decouple the project from the okta-sdk-java a bit more (This might mean a few changes to package names in low level classes, and classes related to Factors).

Granted those are breaking changes from a semver perspective, but they are relatively minor.

**Comment by EarthCitizen** [comment] 2019-03-18 22:43
@bdemers Sorry, yes. I mean't 0.0.4.
